### ISSUE TITLE
Change service type

### ISSUE THREAD

**Issue by anton-dutov** [reactive-tech/kubegres#1]
How to change service type to load balance or node port?

**Comment by alex-arica** [comment]
Thank you for your message. 

It is possible to override the default services created by Kubegres.

When we want to create a cluster of PostgreSql, we create a resource of type "kind: Kubegres". And we set a name to that resource. Let's say for this example the name is "mypostgres".

During deployment of that resource, Kubegres controller checks if a service with name "mypostgres" exists and check if another service with name "mypostgres-replica" exists. If not, Kubegres creates those services by following the templates in this folder:
https://github.com/reactive-tech/kubegres/tree/main/controllers/spec/template/yaml

See the service templates YAML:

- Service template for Primary PostgreSql: https://github.com/reactive-tech/kubegres/blob/main/controllers/spec/template/yaml/PrimaryServiceTemplate.yaml

- Service template for Replica PostgreSql: https://github.com/reactive-tech/kubegres/blob/main/controllers/spec/template/yaml/ReplicaServiceTemplate.yaml

What you can do is to override this behaviour. Before deploying your Kubegres resource, deploy 2 services with name "mypostgres" for the Primary PostgreSql and with name "mypostgres-replica" for Replica PostgfeSql by making sure to follow the properties in the service templates above. Just remove "clusterIP: None" and add the service type that you would like.  

Then deploy your Kubegres resource with name "mypostgres" and since the services with name "mypostgres" and "mypostgres-replica exist, Kubegres will use them.

Note that the name "mypostgres" is just for this example. Obviously, you can set any name to your Kubegres resource.

Please let me know if that helps?

Note that I have not tested Kubegres with other service types. I will give it a go by modifying the service templates above and run the [55 acceptance tests](https://github.com/reactive-tech/kubegres/tree/main/test). If the tests pass, we are good to go.

**Comment by anton-dutov** [comment]
@alex-arica
Thanks for reply, at first look it's seems as temporary workaround. From my point (multi postgres setup) most popular settings should be available to change by CRD - I can explain.

For example: We have 10 postgres clusters with diffirent service types, some for internal use, should be ClousterIp, some others shuld be avalable as node port, third type with defined load balancer ip

First way disadvantages  (change kubegres svc template):

1.it affect all instances, without predefined services

Second way disadvantages (manualy create service definitions):

1. Solve all service and label names manualy
2. Keep creation order
3. Multiple definition files
4. Need  document this way for other admins, instead of self-describing crd

**Comment by alex-arica** [comment]
Thanks for your feedback. Your suggestions are much appreciated.

I understand you have a preference for changing by CRD rather than having to create your own service resources. I understand that point of view.

Currently Kubegres allows overriding default configurations through a custom ConfigMap, as explained here:
https://www.kubegres.io/doc/set-config-map.html

I could provide a way to override the default svc templates from that custom ConfigMap. It would be consistent with how it currently works for other configurations.

What do you think about that approach? 

If you prefer another approach, I would like to get your full feedback about how ideally you would see this configuration to be, with concrete example.

**Comment by alex-arica** [comment]
I have another suggestion, I could add an option in the Kubegres YAML to specify a "serviceType" with possible values: ClusterIP or NodePort or LoadBalancer. The default is ClusterIP.

But "serviceType" would be the only available option. If you want to define a service with additional custom properties (e.g. options available in the Service YAML) then you will have to create your own service resource as mentioned in my first comment. 

Because Kubegres YAML is not the right place to put full service properties.

Please let me know if that would help?

**Comment by Eido95** [comment]
@alex-arica, sorry for re-opening this old one,

However, because the services type is always `ClusterIP`, it is not possible to access the database from outside the k8s cluster (i.e. postgres client on dev machine).

Your suggested "serviceType" option will help make it possible.
