### ISSUE TITLE
Persistent Volumes not reused/Stateful Sets not working properly

### ISSUE THREAD

**Issue by georok** [reactive-tech/kubegres#12]
Hi, couple of days ago I deployed a two-node cluster with the help of the Kubegres operator. I followed the getting started instructions and ended up with two Stateful Sets (mypostgres-1 as primary and mypostgres-2). So far so good. I wanted to enable statistics so I updated the base-kubegres-config map with the following lines in the postgres.conf section:

shared_preload_libraries = 'pg_stat_statements'               # (change requires restart)
pg_stat_statements.max = 10000
pg_stat_statements.track = all

I could not figure out how to restart the pods, the change of the config map was not picked up by the kubegres operator ( I am not sure if it is supposed to) and also kubectl upgrade would not work with the kubegres kind. As there was no documentation about how to do it properly I decided to kill the pods expecting that they would be recreated according to the standard stateful set policy. I started with the slave pod mypostgres-2-0 and it was recreated properly and picked up the changes. When I killed the master (mypostgres-1-0), mypostgres-2 was promoted to be a master, which worked as expected, but mypostgres-1was not recreated. After a while, and quite a bit of confusion on the Kubernetes part, a new pod mypostgres-3 was brought up. 

Now, I had three PVCs, postgres-db-mypostgres-1-0, postgres-db-mypostgres-2-0, postgres-db-mypostgres-3-0 ... and the first one was bound but not used. 

I expected that either pod 1 would be recreated according to the kubernetes stateful set rules, or if that is not possible for some reason, at least the disk would be reused.

Just to be sure, I killed the new master (#2) and after a while I ended up with #3 as master and brand new pod #4 as slave (and four allocated disks)

Regardless of me doing it the right or wrong way, it was a good test because it showed what would happen if  a pod dies.

Am I missing something or this is how it is supposed to work? If the latter is the case, it does not look right.

thanks,

**Comment by alex-arica** [comment]
Thank you for your feedback and the details that you have provided.

You highlighted missing instructions in the Kubegres documentation. It seems like we missed the instructions about how to apply a ConfigMap change to existing pods. The current documentation explains how to apply a ConfigMap changes to new pods but not to existing pods. Sorry for that.

I am going to update the doc, and let me list below the required instructions:

Kubernetes does not notify the Kubegres controller when a ConfigMap is updated. Consequently, when we want to apply  the changes made to a ConfigMap to existing pods then the pods must be restarted manually.

The steps to follow are:

- Update your ConfigMap (e.g. "base-kubegres-config")

- Pause Kubegres controller by running: 
```
kubectl scale --replicas=0 deployment.apps/kubegres-controller-manager -n kubegres-system
```

- Restart the StatefulSets of your Postgres cluster (in this example my cluster's name is "mypostgres" and I have 3 pods running)
```
kubectl rollout restart statefulset mypostgres-1 mypostgres-2 mypostgres-3
```

- Check your pods are in a running state:
```
kubectl get pods 
```

- Resume Kubegres controller by running: 
```
kubectl scale --replicas=1 deployment.apps/kubegres-controller-manager -n kubegres-system
```

The reason why we have to pause Kubegres controller, is to avoid the failover process to trigger when we restart the StatefulSets which will then restart the Pods.

I am going to update Kubegres website with the instructions above.

In regards to the PVCs, by default when a StatefulSet is deleted, Kubernetes does not delete its associated PVC. I think that's the right approach because we do not want to touch to the existing data in case of the deletion of a StatefulSet was made by mistake.

I hope that helps?

**Comment by alex-arica** [comment]
I updated Kubegres documentation's page:
https://www.kubegres.io/doc/override_default_configs.html

Please see the section "Note about applying ConfigMap changes to existing PostgreSql pods".

**Comment by georok** [comment]
Hi Alex, 
Thank you for the prompt reply. 
Providing the instructions definitely helps. Unfortunately it does not resolve the main issue.
I did not kill the stateful set, I killed the pod managed by that stateful set. The actual stateful set has to recreate exactly the same pod (according to the Kubernetes documentation). I have a single instance PostgreSQL deployed as StatefulSet and I tested the theory. Immediately after I killed the pod the StatefulSet recreated exactly the same pod. 

"The PVC of the promoted Pod remains the same when it becomes a Primary. I think it would be unexpected to change the PVC of a Pod after if becomes a Primary." - Sorry if you misunderstood me. I did not mean to flip the PVCs -I do not believe that is possible. What I meant is that when Pod2 (and PVC2 for the sake of the example) becomes primary, the controller must bring again Pod1 (with PVC1) as secondary and not leave PVC1 unclaimed and bring a brand new POD3 (with PVC3) ... and keep on doing that every time the primary pod dies.

Creating new stateful set every time and not reusing the existing disks may be OK for small datasets, but imagine a database with size in hundreds of GB or in TB.

I have to admin that I haven't checked any other PostgreSQL Operators to see if what I expect is at all possible, but if as you are saying this is not possible, then I will have to drop the whole idea of a cluster PostgreSQL Operator on Kubernetes. 
To keep on creating new Stateful Sets does not work for me.

thanks,
George

**Comment by alex-arica** [comment]
Thank you for your message.

When you manually deleted Pod 1, Kubegres triggered the failover process promoting Pod 2 as Primary. And since you required a cluster of 2 instances of postgres then Kubegres has created a Pod 3 as a Replica.

Kubernetes doesn't check StatefulSet, it relies on the state of the Pods. If a Pod is not available, Kubegres triggers the failover process assuming that all components in regards of that Pod are comprised. This is why the PVC is not reused.

If you manually deleted a Pod, Kubegres sees it as unstable and doesn't reuse it. For Kubegres there is no way to know if you manually deleted a Pod or if it's a genuine production issue.

This is how the failover works with Kubegres.

If your aim was the restart your Pod so that the changes to ConfigMap is used, then please follow the instructions in my previous comment.

**Comment by georok** [comment]
Thank you, Alex.

I understand what you are saying.
I will close the issue as I obviously cannot achieve what I need with this solution.
Thank you for taking the time to explain it to me.
Much appreciated.

**Comment by alex-arica** [comment]
I would like to thank you for raising this ticket because it highlighted important details missing from Kubegres documentation. 

Thanks to you, the documentation was improved.

In regards to your suggestion, I think it makes sense. And if Kubernetes was providing to the operators more fine grained details such as for example whether the blocks of a PVC volume are corrupted or not, then from the controller we could programmatically decide whether we could reuse PVCs and StatefulSets.

Based on the few details that we have from Kubernetes, we decided to consider any Pod reported as unhealthy and its associated components (e.g. PVC) as compromised.

**Comment by alex-arica** [comment]
I am working on a new feature which will allow to configure the behaviour of PVC when a failover happens.

A new field "failover.pvc" will be available in the YAML where it will be possible to specify what will become of the PVC of a failing instance of Postgres pod.  

As part of the available options for the field "failover.pvc", there would be:

- "keep": the default option currently with Kubegres where PVC are kept but not reused for safety and investigation reasons

- "delete": the PVC will be deleted

- "reuse": if the state of the PVC is healthy, it will be reused by the newly created replica pod. I think that matches with your suggestion?

If that's the case, I am going to reuse this ticket for the option "reuse".

**Comment by heschlie** [comment]
@alex-arica has this been implemented yet? I am running my cluster on preemptible nodes in GKE. And while this works, I end up with a large number of PVCs as the statefulsets keep climbing in number. This suggestion might be what you imply by reuse, but I feel like you should be able to to promote a replica, see the old master statefulset recover, and set it as a replica. for example:

- Statefulset-1-0 is created, set to master
- Statefulset-2-0 is created, set to replica
- Statefulset-1-0 is terminated due to node removal
- Statefulset-2-0 is promoted to master
- Statefulset-1-0 comes back up on new node, is set to replica

If that is not possible then it seems like it might be better to not use a statefulset, but just a deployment and have it attach the PVCs which kubegres could map and monitor to prevent PVC sprawl.

**Comment by alex-arica** [comment]
Thank you for your message. This ticket was closed because no response was received from the user who initially requested it. I made a suggestion in my last message to that user and as no response was received, we assumed that there was a lack of interest.

I invite you to create a new ticket about reusing PVC. And I will add it to the roadmap.

**Comment by th-turk** [comment]
> I am working on a new feature which will allow to configure the behaviour of PVC when a failover happens.
> 
> A new field "failover.pvc" will be available in the YAML where it will be possible to specify what will become of the PVC of a failing instance of Primary Postgres pod.
> 
> As part of the available options for the field "failover.pvc", there would be:
> 
> * "keep": the default option currently with Kubegres where PVC are kept but not reused for safety and investigation reasons
> * "delete": the PVC will be deleted
> * "reuse": if the state of the PVC is healthy, it will be reused by the newly created Replica pod. I think that matches with your suggestion?
> 
> If that's the case, I am going to reuse this ticket for the option "reuse".

Hey Alex. 
 Is there any improvement about this feature.  that would be so helpful to avoid many unused PVC

**Comment by armando1988** [comment]
Hello Alex,
we would also be very interested in having this feature.

In the long run we have many orphaned PVCs that we need to remove manually.

Thanks

**Comment by teebu** [comment]
reuse sounds like a great idea. having half a dozen unused pvcs because of a pod restart is not good, especially when they are large.

**Comment by rafaelvslobato** [comment]
Any news on when this feature will be ready?

**Comment by dev-mich** [comment]
Hi, i have this same exact problem, lot of orphan pvc that i have to manually remove once in a while, any solution to this?

**Comment by alex-arica** [comment]
We are going to have more dev resources available for Kubegres during end of November. 
We will implement this feature in priority then.

**Comment by dev-mich** [comment]
Thank you Alex!
