### ISSUE TITLE
The API version batch/v1beta1 does no longer exist since Kubernetes v1.25

### ISSUE THREAD

**Issue by IcarusCoding** [reactive-tech/kubegres#128]
The beta API version used for CronJob no longer exists and must therefore be replaced by the batch/v1 version as stated in the [Deprecated API Migration Guide](https://kubernetes.io/docs/reference/using-api/deprecation-guide/#cronjob-v125).

**Comment by alex-arica** [comment]
Thank you. 
I will release a new version of Kubegres next week in order to use the new CronJob in batch/v1

**Comment by IcarusCoding** [comment]
I also opened a PR for it

**Comment by alex-arica** [comment]
Thank you. I will test your PR locally next week and run all the unit/acceptance tests.

**Comment by alex-arica** [comment]
I did not merge your changes because I had to upgrade the framework Kubebuilder from version 3.0.0 to 3.6.0 and there were too many changes.

Kubegres 1.16 is available and it is compatible with Kubernetes 1.25 and it uses the new CronJob:
https://github.com/reactive-tech/kubegres/releases/tag/v1.16
