### ISSUE TITLE
Postgres 16 error due to eliminated promote_trigger_file config parameter

### ISSUE THREAD

**Issue by daku** [reactive-tech/kubegres#162]
root@quiche:~# mk logs mypostgres-2-0 --all-containers
23/09/2023 06:11:18 - Attempting to copy Primary DB to Replica DB...
ls: cannot access '/var/lib/postgresql/data/pgdata': No such file or directory
23/09/2023 06:11:18 - Copying Primary DB to Replica DB folder: /var/lib/postgresql/data/pgdata
23/09/2023 06:11:18 - Running: pg_basebackup -R -h mypostgres -D /var/lib/postgresql/data/pgdata -P -U replication;
waiting for checkpoint
23134/23134 kB (100%), 0/1 tablespace
23134/23134 kB (100%), 1/1 tablespace
23/09/2023 06:11:18 - Copy completed

PostgreSQL Database directory appears to contain a database; Skipping initialization

2023-09-23 06:17:16.179 GMT [1] FATAL:  unrecognized configuration parameter "promote_trigger_file"

**Comment by alex-arica** [comment]
Thank you for reporting this issue. 

Since PostgreSql 16 the feature allowing to promote a Replica using the file provided by the property "promote_trigger_file" was removed by PostgreSql developers.

We are going to release a new version of Kubegres today which will use it the tool provided by Postgres:  "pg_ctl promote".

This change is compatible with the previous versions of PostgreSql.

**Comment by alex-arica** [comment]
A new version of Kubegres is available compatible with Postgres 16 :
https://github.com/reactive-tech/kubegres/releases/tag/v1.17
