### ISSUE TITLE
1st replica of postgres stay in pending

### ISSUE THREAD

**Issue by PauloLaScience** [reactive-tech/kubegres#4]
Hi,
1st replica of postgres stay in pending: mypostgres-2-0 in Kubernetes dashboard with this message:
0/1 nodes are available: 1 node(s) didn't match pod affinity/anti-affinity, 1 node(s) didn't match pod anti-affinity rules.

**Comment by alex-arica** [comment]
Hi,

Thank you for message.

Could you please send me the output for the following commands?

kubectl get nodes -o wide

And

kubectl get pods -o wide

Kubegres deploys one instance of postgrsql per node. If the kubernetes cluster has, let's say, 2 nodes and 3 postgresql instances are deployed then only 2 postgresql instances will be deployed, one on each node. The remaining third postgresql instance will be pending until a third node is available.

Thank you.

**Comment by PauloLaScience** [comment]
I'm deploying on minikube 
So only one node.
```bash
kubectl get nodes -o wide
NAME       STATUS   ROLES                  AGE     VERSION   INTERNAL-IP      EXTERNAL-IP   OS-IMAGE               KERNEL-VERSION   CONTAINER-RUNTIME
minikube   Ready    control-plane,master   4h49m   v1.20.2   192.168.50.100   <none>        Buildroot 2020.02.10   4.19.171         docker://20.10.4
kubectl get pods -o wide
NAME             READY   STATUS    RESTARTS   AGE     IP           NODE       NOMINATED NODE   READINESS GATES
mypostgres-1-0   1/1     Running   0          4h29m   172.17.0.6   minikube   <none>           <none>
mypostgres-2-0   0/1     Pending   0          4h27m   <none>       <none>     <none>           <none>
```

**Comment by alex-arica** [comment]
Ok that makes sense.

May I suggest you "kind"? It allows testing multi nodes cluster locally.

https://kind.sigs.k8s.io/docs/user/quick-start/

**Comment by alex-arica** [comment]
Is my suggestion sufficient or would you suggest that Kubegres YAML should provide the option to disable pod affinity/anti-affinity ?

**Comment by alex-arica** [comment]
Hi, I updated Kubegres official documentation here: https://www.kubegres.io/doc/getting-started.html

I added the following notes, as follows:

**Note about Kubegres and Kubernetes nodes**

If you are testing Kubegres on your local Kubernetes cluster, you need to use a tool such as [Kind](https://kind.sigs.k8s.io/) which allows running a Kubernetes cluster with multiple nodes. At the time of writing this tutorial, Minikube only allowed running a Kubernetes cluster with a single node and consequently it would not be the right tool to test Kubegres.

The reason is, Kubegres is using pod anti-affinity based on node, which means each PostgreSql instance is deployed on different node. For the same PostgreSql cluster, we cannot have 2 PostgreSql instances on the same node. This approach is to ensure that in the case when a physical node is not available, we have databases available on other physical nodes. This guarantees a stronger resiliency and availability of the database.

Consequently, if you deploy a cluster of PosgreSql with 3 instances, you have to make sure that your cluster has at least 3 nodes. 


Please close this ticket if you are happy with the above.

**Comment by PauloLaScience** [comment]
I'm testing Kind but I have some issue to running it because I'm using podman on Fedora.

But your change in documentation is more than clear.
thanks

**Comment by alex-arica** [comment]
@PauloLaScience I am pleased to announce that you will be able to deploy multiple instances of PostgreSql on a Kubernetes cluster with a single node (e.g. Minicube).
