### ISSUE TITLE
Missing Docs on Volumes

### ISSUE THREAD

**Issue by kahunacohen** [reactive-tech/kubegres#45]
Great product!

I'd like to know more on where and how the postgres data is stored. I understand this has to do with a PVC, but more in the docs would be great. I'd be happy to issue a PR for that.

I see mentions of "pvc"s and "persistent volume claim"s in the kubegres.yaml, but how does this work? For example if I am running locally on minikube, where is the data stored? E.g.:

```bash
$ kubectl get sc              

NAME                 PROVISIONER                RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
standard (default)   k8s.io/minikube-hostpath   Delete          Immediate           false                  12d
```

What if in production I wanted to store the data on, say, a GCE bucket? How would I go about doing this?

**Comment by alex-arica** [comment]
Thank you for your kind feedback.

In the [Getting Started](https://www.kubegres.com/doc/getting-started.html) page, I mentioned the following:
"
2) Check storage class

Kubegres requires a storage class in order to create PV (Persistent Volume) and PVC for each instance of PostgreSql. Please run the following command to check a storage class exist in the Kubernetes cluster: ...
"

Perhaps in the doc section above I could have mentioned how Kubegres set storageClass and Kubernetes creates PV and PVC. Please let me know if that would help.

By default, when you do not specify the field storageClassName, Kubegres finds the default storage class of the Kubernetes cluster and assigns it. But you can also assign the storageClass manually using the field "storageClassName". There are more details about that field here: https://www.kubegres.com/doc/properties-explained.html

Once the storageClass is assigned, Kubernetes automatically provisions PV and PVC for each Pod. You can check the PV and PVC created as follows:
```
kubectl get pv, pvc
```

The official Kubernetes doc has a good page about that topic:
https://kubernetes.io/docs/concepts/storage/storage-classes/

Please let me know if that helps.

**Comment by kahunacohen** [comment]
Thanks for the quick help! This is the only operator of this kind I could get up and running without a hitch. Great potential, and we are experimenting with it for our projects. Yes, I think at least a link to the storageClassName and volumeMount yaml props would be very helpful.

Would you like me to issue a PR with this change?

**Comment by alex-arica** [comment]
I am glad to hear you are satisfied about Kubegres.
I can update the documentation for you. This week I am working full-time on this project. 

Once it's updated I will let you know and you can tell me if it's satisfactory.

Alternatively, if you really want to raise a PR it's ok too.

**Comment by alex-arica** [comment]
In the [Getting Started page](https://www.kubegres.io/doc/getting-started.html), under the YAML example I added the following paragraph:

""
In the YAML above, under the field "spec.database" we only specified the field "size". But you can also specify the fields "storageClassName" and "volumeMount". There are more details about those fields [in this page](https://www.kubegres.io/doc/properties-explained.html).
If you do not specify the field "storageClassName", Kubegres finds the default storage class of the Kubernetes cluster and assigns it. But you can also assign a value for that field manually. Once the storageClass is assigned, Kubernetes automatically provisions a PV and a PVC for each Postgres Pod. You can check the PV and PVC created as follows: 
""
```
kubectl get pv, pvc
```

Please close this issue if you are happy about it. Otherwise, I am happy to make additional changes.

**Comment by spencerdcarlson** [comment]
Something that I ran into was when wanting to delete the existing volumes I needed to delete the PV, remove the finalizers, and delete the PVC. I'm not sure if there is a more graceful way to "reset" the volumes. Missing one of those steps causes issues when trying to initialize a new cluster
