### ISSUE TITLE
How is postgres service Created?

### ISSUE THREAD

**Issue by kahunacohen** [reactive-tech/kubegres#48]
I don't think it is entirely clear from the docs how the postgres service is created. Is it from the `metadata.name` field in the kubegres yaml? In the docs this is set to `mypostgres`.

I changed this to "postgres," took down the pods (using skaffold) and checked there were no postgres services. I brought the app back up and the `mypostgres` service was created a-new.

I installed kubegres, by downloading the yaml from https://raw.githubusercontent.com/reactive-tech/kubegres/v1.10/kubegres.yaml and listing it for skaffold.

I grepped my repo for "mypostgres" and there are no instance of it left, so I'm not sure how a service with this name is being created.

**Comment by alex-arica** [comment]
Thank you for your message.

That's correct, the services are created using the field "name" in the YAML. 

In the [Getting started ](https://www.kubegres.io/doc/getting-started.html)section there are some details about services. Please see the section "6) Connect client apps to PostgreSql".

And more details can be found in the section "Use case" of the page [Replication and Failover](https://www.kubegres.io/doc/replication-and-failover.html).

I do not think you can change that field once a cluster is deployed.

**Comment by kahunacohen** [comment]
Right that's my point. I took down all the resources, started them back up and still see the service, "mypostgres", even though the name field is no longer "mypostgres" in the local yaml. Any ideas why this may be happening? I would expect the service to be called "postgres"

**Comment by alex-arica** [comment]
Kubegres does not support renaming an existing cluster of Postgres. Therefore the value of the field "name" cannot be changed in the YAML.

In the other hand, it is possible to create many separate clusters of Postgres as long as each YAML of "kind: Kubegres" has a different value for the field "name".

**Comment by kahunacohen** [comment]
I use skaffold, so whatever resources in yaml I define, it deletes for me (I think). When you say "cluster" of postgres, do you mean the resources created when applying https://raw.githubusercontent.com/reactive-tech/kubegres/v1.10/kubegres.yaml (the operator)? What specific resources would I have to delete to make minikube think I have a brand new postgres cluster?

Surely in development I should be able to start from scratch when setting it all up then deploy it to production when satisfied.

**Comment by alex-arica** [comment]
I didn't mean the resources created by the operator. If you delete the resources created by the operator, Kubernetes will not delete the cluster of Postgres.

By cluster of Postgres, I was talking about the resource of kind 'kubegres'.

Each time we want to create a cluster of Postgres, we create a YAML of kind 'kubegres'. Each cluster of Postgres is identified by the unique name given to the YAML (e.g. 'postgres') and the namespace.

If your aim is to delete an existing cluster of Postgres, you can run:
```
kubeclt delete kubegres [unique name]
```

For example:
```
kubeclt delete kubegres postgres
```

The above will delete all resources created for that cluster of Postgres identified with the unique name 'postgres'. By resources I mean the Pods, Statefulsets, Services etc...  It will not delete the controller/operator Kubegres.

The only resources that you have to remove manually are PV and PVC. There is one PV and one PVC created for each Pod. The reason why we don't remove those is because we don't want to remove the databases. In a future version of Kubegres it will be possible to set an option in the YAML so that they are automatically removed too.

**Comment by kahunacohen** [comment]
Great feedback. That did it. Also deleted the kubegres-system namespace. Now the new service name gets picked up.

**Comment by alex-arica** [comment]
Nice one 👍

**Comment by alex-arica** [comment]
At the end of the page [Getting started](https://www.kubegres.io/doc/getting-started.html), I added a new section: "7) Delete a cluster of Postgres".
