### ISSUE TITLE
Database rolled back

### ISSUE THREAD

**Issue by edwardzjl** [reactive-tech/kubegres#55]
We experienced a rollback yesterday and some data was lost.

I found that some pods were re-arranged.

We used to have postgres-1-0, postgres-2-0 and postgres-3-0, and now we have postgres-2-0 (restarted), postgres-3-0 and postgres-4-0 (new):

![image](https://user-images.githubusercontent.com/7287580/137066653-9973eef5-2074-4651-9c01-5d9e7d559d25.png)

Also, the volumes were updated. We tried to expand volumes from 200m to 10G, but only volume 3 got expanded (like the demo in [this issue](https://github.com/reactive-tech/kubegres/issues/34)).

Now we have 4 volumes all having 10G capacity (I assume volume postgres-db-postgres-1-0 have the data we lost, as we don't have important data now, is it ok I just delete the pv and pvc?)

![image](https://user-images.githubusercontent.com/7287580/137066982-5a58b9b9-1a49-47ee-bffd-d4209cb1049a.png)

We did not update kubegres or kubernetes, nor did we restarted the kubegres deployment, it happens automatically.

Here is the controller log:

![image](https://user-images.githubusercontent.com/7287580/137068097-b66cacbe-2670-4fb6-897f-8cb26c219fa1.png)

**Comment by alex-arica** [comment]
Unfortunately without the logs it's very difficult to know what happened. 

My guess is after updating the size of the database in YAML, Kubegres prior to version 1.11 tried to update the size but Statefulsets were not getting refreshed due to Kubernetes lack of features on that side.

Consequently, after sometime Kubegres timed out the resize operation. Usually the message displayed when this happens is to ask the admin using Kubegres to fix the issue manually.

What is not clear is why replication would stop. I don't think that's related to database's resize operation. Most likely Postgres logs would have provided some clues.

I am closing this issue because of missing logs.
