### ISSUE TITLE
Postgres versions

### ISSUE THREAD

**Issue by cliffordt3** [reactive-tech/kubegres#67]
Hello,
I had a question about supported Postgres versions. Your project documentation states:
 "It works with the PostgreSql containers created by the Docker Official Images team (version 12.4 or higher)."  

I was curious if there was anything special about 12.4 specifically. Does something in the operator rely on  features that were introduced in version 12.4? I'm asking because we are interested in using Kubegres but are currently running the latest 10.x version of Postgres and a version upgrade is not immediately possible.

**Comment by alex-arica** [comment]
Thank you for your message.

Kubegres creates a file as defined in the property "promote_trigger_file" to tell PostgreSql to promote a Replica to a Primary. The property promote_trigger_file is available from version 12.x

Please let me know if that helps.

**Comment by cliffordt3** [comment]
Thanks. So would it be possible to use Kubegres with the official 10.x Postres images with  built-in logical replication?

**Comment by alex-arica** [comment]
Some acceptance tests do not pass with Postgres versions under 12.4 

What particularly fails is the promotion of a Replica to a Primary. In that case you could use Kubegres by disabling failover. 

A flag can be used to disable failover:
https://www.kubegres.io/doc/properties-explained.html#spec_failover

If that flag is set to true, the issue is, if there is a prod issue with Primary, Kubegres would not promote a Replica to a Primary automatically. It is possible to manually tell to Kubegres to promote a Replica by setting the name of a Pod to the field "promotePod".

**Comment by cliffordt3** [comment]
This is really helpful. Thank you.
